# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserPlayground < Formula
  desc "Evans: more expressive universal gRPC client"
  homepage "https://evans.syfm.me"
  url "http://github.com/ktr0731/goreleaser-playground/releases/download/v0.3.1/goreleaser-playground_darwin_amd64.tar.gz"
  version "0.3.1"
  sha256 "6e509b152fa2d7734229f041b2e7d85da4901f20473655b836e01b58f369e176"

  def install
    bin.install "goreleaser-playground"
  end
end
